# Generated by Django 4.2 on 2024-10-18 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=69, verbose_name='Product')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='Product Photo')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('short_description', models.CharField(db_index=True, max_length=369, null=True, verbose_name='Short Description')),
                ('description', models.TextField(db_index=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, default='', max_length=100, unique=True, verbose_name='URL Title')),
                ('is_active', models.BooleanField(verbose_name='Active Product')),
                ('is_delete', models.BooleanField(verbose_name='Delete Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=69, verbose_name='Title Category')),
                ('url_title', models.CharField(db_index=True, max_length=100, verbose_name='URL Title Category')),
                ('is_active', models.BooleanField(verbose_name='Active Category')),
                ('is_delete', models.BooleanField(verbose_name='Delete category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product Visit',
                'verbose_name_plural': 'Product Visits',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_category', to='product_module.productcategory', verbose_name='Product Categories'),
        ),
    ]
