# Generated by Django 4.2 on 2024-10-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Name Website')),
                ('site_url', models.URLField(verbose_name='URL Website')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('logo', models.ImageField(blank=True, upload_to='images/site-setting/', verbose_name='Logo')),
                ('email', models.JSONField(blank=True, default=list, verbose_name='Email')),
                ('copy_right', models.TextField(blank=True, verbose_name='Copy Right')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('is_main_setting', models.BooleanField(verbose_name='First Setting')),
            ],
            options={
                'verbose_name': 'Setting Website',
                'verbose_name_plural': 'Setting',
            },
        ),
    ]
