# Generated by Django 4.2 on 2024-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80, verbose_name='Full Name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
