# Generated by Django 5.1.2 on 2024-12-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_chat_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestep',
            new_name='timestamp',
        ),
    ]
