# Generated by Django 4.2 on 2024-10-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Category Title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL In Category Title')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Children', to='article_module.articlecategory')),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('short_description', models.CharField(max_length=350, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='Image Article')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL In Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('ceated_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('categories', models.ManyToManyField(to='article_module.articlecategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
