# Generated by Django 5.1.2 on 2025-08-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='categories',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
