# Generated by Django 5.1.2 on 2024-12-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='ceated_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date And Time'),
        ),
    ]
