# Generated by Django 5.1.2 on 2025-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_last_login_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_initiated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email change initiated at'),
        ),
        migrations.AddField(
            model_name='user',
            name='old_email_verification_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Old email verification code'),
        ),
        migrations.AddField(
            model_name='user',
            name='old_email_verified',
            field=models.BooleanField(default=False, verbose_name='Old email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/', verbose_name='Avatar'),
        ),
    ]
